### ISSUE TITLE
1.19.2 崩溃bug

### ISSUE THREAD

**Issue by bddjr** [Bunnui/Fabric-Bedrock-Miner#1]
两层基岩，破坏上方基岩，然后直接尝试破坏下方基岩，随后破坏失败，直接崩溃。

**Comment by bddjr** [comment]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-12-28 15:52:19
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "pos" is null
	at yan.lx.bedrockminer.utils.BlockPlacer.placement(BlockPlacer.java:36)
	at yan.lx.bedrockminer.utils.BlockPlacer.simpleBlockPlacement(BlockPlacer.java:27)
	at yan.lx.bedrockminer.utils.TargetBlock.updateHandler(TargetBlock.java:163)
	at yan.lx.bedrockminer.utils.TargetBlock.updater(TargetBlock.java:95)
	at yan.lx.bedrockminer.utils.BreakingFlowController.updater(BreakingFlowController.java:145)
	at yan.lx.bedrockminer.utils.BreakingFlowController.tick(BreakingFlowController.java:126)
	at net.minecraft.class_636.handler$zel002$init(class_636.java:1600)
	at net.minecraft.class_636.method_2927(class_636.java)
	at net.minecraft.class_310.method_1574(class_310.java:1799)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at yan.lx.bedrockminer.utils.BlockPlacer.placement(BlockPlacer.java:36)
	at yan.lx.bedrockminer.utils.BlockPlacer.simpleBlockPlacement(BlockPlacer.java:27)
	at yan.lx.bedrockminer.utils.TargetBlock.updateHandler(TargetBlock.java:163)
	at yan.lx.bedrockminer.utils.TargetBlock.updater(TargetBlock.java:95)
	at yan.lx.bedrockminer.utils.BreakingFlowController.updater(BreakingFlowController.java:145)
	at yan.lx.bedrockminer.utils.BreakingFlowController.tick(BreakingFlowController.java:126)
	at net.minecraft.class_636.handler$zel002$init(class_636.java:1600)
	at net.minecraft.class_636.method_2927(class_636.java)

-- Affected level --
Details:
	All players: 1 total; [class_746['bddjr'/1, l='ClientLevel', x=26.32, y=-62.00, z=-13.62]]
	Chunk stats: 1024, 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-63,0), Section: (at 0,1,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 6191 game time, 6191 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, armorchroma/alternative-icons, continuity/default, continuity/glass_pane_culling_fix, XeKr 原版红显16~19plus2.4.zip, [1.19.1]MASA全家桶汉化包.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2088330184 bytes (1991 MiB) / 3254779904 bytes (3104 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 4.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2647
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37480.28
	Virtual memory used (MB): 20837.17
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx10240m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.1-fabric0.58.5-1.3.1
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.4.62
		armorchroma: Armor Chroma 1.2.3
		auto_login: Auto Login Command 2.0.0
		autoreconnect: AutoReconnect 2.1.0-beta
		axolotlitemfix: Axolotl Item Fix 1.1.4
		bedrockminer: Bedrock Miner 1.0.0
		boostedbrightness: Boosted Brightness 2.1.2
		bsvsb: Better Sodium Video Settings Button 3.0.2
		carpet: Carpet Mod 1.4.84
		carpet-extra: Carpet Extra 1.4.84
		carpet-tctc-addition-1_19_2: Carpet TCTC Addition for 1.19.2 2.0.182+c98605f-beta
		carpet-tis-addition: Carpet TIS Addition 1.44.0
			conditional-mixin: conditional mixin 0.3.2
		cherishedworlds: Cherished Worlds 6.0.1+1.19.2
		chesttracker: Chest Tracker 1.1.18
			libgui: LibGui 6.3.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			whereisit: Where Is It 1.14.13
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		colormeoutlines: Color Me Outlines 1.1.1
		continuity: Continuity 2.0.1+1.19
		enchlevel-langpatch: Enchantment Level Language Patch 1.2.3
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		fabric-api: Fabric API 0.69.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.4+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.3+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.36+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.10+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.13+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.21+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.3+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.2+574a764890
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.30+b0bc9a6790
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.12
		fpsreducer: FPS Reducer 1.19.2-2.1
		ias: In-Game Account Switcher 8.0.1
		imblocker: IMBlockerFabric 1.0.19
		indium: Indium 1.0.9+mc1.19.2
		inventoryprofilesnext: Inventory Profiles Next 1.9.0
		iris: Iris 1.4.5
			io_github_douira_glsl-transformer: glsl-transformer 1.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		itemmodelfix: Item Model Fix 1.0.3+1.19
		java: Java HotSpot(TM) 64-Bit Server VM 17
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 2.0.0
		litematica: Litematica 0.12.6
		lithium: Lithium 0.10.4
		magiclib: MagicLib 0.5.39
		magiclib-1_19_2: MagicLib for 1.19.2 0.6.193+84fd02e-beta
		malilib: MaLiLib 0.13.0
		masa_gadget_mod: Masa Gadget 3.0.0-beta+1bf6939
			masa_gadget_mod-1_19_2: Masa Gadget for 1.19.2 3.0.0-beta+1bf6939
		mcwifipnp: LAN World Plug-n-Play 1.5.6
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.1.2
		ommc: Oh My Minecraft Client 0.5-beta+8215759
			ommc-1_19_2: Oh My Minecraft Client for 1.19.2 0.5-beta+8215759
		opitems: Op Items 1.2.2
		orderly: Orderly 2.0.1-alpha.2+custom-1.19
		pca: Plusls carpet addition mod 0.2.5-beta+827168a
			multiconnect-api: MultiConnect API 1.5.10
		replaymod: Replay Mod 1.19.2-2.6.10
		roughlyenoughitems: Roughly Enough Items 9.1.580
			error_notifier: Error Notifier 1.0.9
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.15+mc1.19.2-build.85
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		tiefix: TieFix 1.11.0
		tweakeroo: Tweakeroo 0.14.3
		tweakmyclient: Tweak My Client 3.2.268+fc2ad10-stable
			tweakmyclient-1_19_2: Tweak My Client for 1.19.2 3.2.268+fc2ad10-stable
		uiinputundo: UI Input Undo 1.2.0
		wi_zoom: WI Zoom 1.4-MC1.19.2
		xaerominimap: Xaero's Minimap 22.17.0
		xaeroworldmap: Xaero's World Map 1.28.7
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.19.2-Fabric 0.14.12
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 526.47, NVIDIA Corporation
	Window size: 3840x2066
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, armorchroma/alternative-icons (incompatible), continuity/default, continuity/glass_pane_culling_fix, file/XeKr 原版红显16~19plus2.4.zip, file/[1.19.1]MASA全家桶汉化包.zip
	Current Language: 简体中文 (中国大陆)
	CPU: 12x Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['bddjr'/1, l='ServerLevel[新的世界]', x=26.32, y=-62.00, z=-13.62]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental

**Comment by Bunnui** [comment]
视乎是因为Pos传入null值导致的，有时间在看看

**Comment by Bunnui** [comment]
已修复，下载地址：[releases](https://github.com/Bunnui/Fabric-Bedrock-Miner/releases)
