### ISSUE TITLE
[question] block break list?

### ISSUE THREAD

**Issue by krispyking24** [Bunnui/Fabric-Bedrock-Miner#11]
where's the list of blocks the mod checks for to be able to break? i have my own fork where i added blocks to the list but in the rewrite i cant find the path to the list ik the old path was "src/main/java/yan/lx/bedrockminer/utils/BreakingFlowController.java" but the list isnt in that file in the new version

**Comment by Bunnui** [comment]
I don't know about your branch situation, the list of allowed corrupting is usually in BreakingFlowController or BedrockMinerMod. At present, I have completed the function of adding the list of squares using the command, and I am debugging. After completion, I will push the main branch. Note: For server security, I will restrict some squares.

**Comment by Bunnui** [comment]
https://github.com/Bunnui/Fabric-Bedrock-Miner/releases/tag/v1.19.4

**Comment by Bunnui** [comment]
https://github.com/krispyking24/Fabric-Bedrock-Miner/blob/42697a3f91863327b5376a695c042226b72fc50e/src/main/java/yan/lx/bedrockminer/BedrockMinerMod.java#L19

**Comment by Bunnui** [comment]
https://github.com/krispyking24/Fabric-Bedrock-Miner/blob/42697a3f91863327b5376a695c042226b72fc50e/src/main/java/yan/lx/bedrockminer/utils/BreakingFlowController.java#L49


https://github.com/krispyking24/Fabric-Bedrock-Miner/blob/42697a3f91863327b5376a695c042226b72fc50e/src/main/java/yan/lx/bedrockminer/utils/BreakingFlowController.java#L31
