### ISSUE TITLE
Mismatch in destroy block pos:...

### ISSUE THREAD

**Issue by MrLock9** [Bunnui/Fabric-Bedrock-Miner#15]
Hello Bunnui, 
Me and my friend have been using this on our server, with some success. For me, the mod works fine (~10ms ping), but for my friend it doesn't work, (~100ms ping). Tried opping him to further bypass server anticheat (which has been disabled via carpet), no success.
Issue he has is "Failed to place piston"

Server: 1.19.4, fabric, some carpet features enabled

**Comment by Bunnui** [comment]
提示"Failed to place piston"是因为活塞没有放置的条件，在相关代码中，它会检查目标方块的上方和活塞伸出的位置是可以被替换的，否者它将提示"Failed to place piston"
```
            case FIND_PISTON_POSITION -> {
                pistonBlockPos = blockPos.up();
                // 检查活塞能否放置
                if (CheckingEnvironmentUtils.has2BlocksOfPlaceToPlacePiston(world, blockPos)) {
                    Debug.info("[%s][%s][状态处理][查找活塞位置]: 完成, %s", id, count, pistonBlockPos);
                } else {
                    Debug.info("[%s][%s][状态处理][查找活塞位置]: 失败", id, count);
                    MessageUtils.setOverlayMessageKey("bedrockminer.fail.place.piston");   // 无法放置活塞
                    status = Status.FAILED;    // 失败状态
                    return false;
                }
                status = Status.WAIT_GAME_UPDATE;  // 等待更新状态
            }
```

```
        BlockPos pos1 = blockPos.up();          // 活塞位置
        BlockPos pos2 = blockPos.up().up();     // 活塞臂位置
        // 获取硬度,应该是活塞位置处有其他方块吧？
        if (world.getBlockState(pos1).getHardness(world, pos1) == 0) {
            BlockBreakerUtils.breakPistonBlock(pos1);
        }
        // 判断活塞位置和活塞臂位置是否可以放置
        return world.getBlockState(pos1).getMaterial().isReplaceable() && world.getBlockState(pos2).getMaterial().isReplaceable();
```

您可以提供一下游戏运行日志吗？游戏中输入`/bedrockMiner debug true` 开启调试模式，他会在游戏的后台控制台中打印日志信息。

**Comment by Bunnui** [comment]
The prompt 'Failed to place piston' may not be related to network latency. This prompt indicates that there is a block above the current target block, which is causing the failure!

**Comment by Bunnui** [comment]
I have modified the way to check the placement situation. You can try the version I just modified

https://github.com/Bunnui/Fabric-Bedrock-Miner/suites/13078560881/artifacts/709591063
