### ISSUE TITLE
[功能建议]活塞侧面破基岩支持

### ISSUE THREAD

**Issue by BackWheel** [Bunnui/Fabric-Bedrock-Miner#16]
目前该mod仅支持破坏活塞下方的基岩，当尝试破坏活塞四周的基岩时，mod会显示无法放置活塞。能否添加使用活塞破坏侧面基岩的功能？

**Comment by Bunnui** [comment]
曾经尝试过侧面破坏，但由于调用放置方块的API时，方向无法准确放置，故所以没有继续开发。

目前观察到的原因是方块因为放置前，服务端视角不正确所导致，虽然模组发送了改变服务端玩家视角的数据包（只有上下放置正确，其他方向放置是跟随客户端视角方向放置的），客户端他自己会一直发送修改视角数据包，导致模组的发包顺序不一致，所以在放置方块的时候使用了客户端发送数据包的视角进行放置。

**Comment by Bunnui** [comment]
我尝试了劫持发包队列，以保证放置发包顺序，但还是会发生这个状况，应该是修改视角和交互数据包发送事件较短，修改视角未及时更新服务端玩家视角导致交互放置方块的时候使用到了还未更新的视角值所致，不利于其他方向开发，所以暂时搁置，当可以精准放置方块的时候再考虑开发

**Comment by Bunnui** [comment]
暂时无法实现同tick中精准放置方块方向，暂不考虑。

**Comment by LXYan2333** [comment]
确实无法在一个tick内支持活塞的任意方向放置，主要原因可以看 https://github.com/LXYan2333/Fabric-Bedrock-Miner/blob/main/doc/related%20minecraft%20quirk.md
解决方法是发送带有yRot的数据包后，等待服务端tick玩家一次，同步yRot和yHeadRot，再发送放置活塞的数据包，才能在正确方向上放置活塞。在这两个数据包之间的所有改变yRot的数据包都需要劫持并将xRot和yRot设置为放置活塞需要的方向后再发给服务端。
可以看我的解决方法：https://github.com/LXYan2333/Fabric-Bedrock-Miner/blob/e12e46200349cd86c45e2a10850d2c074b48d127/src/client/kotlin/com/github/lxyan2333/bedrockminer/client/breaking/approach/VanillaAllDirectionApproach.kt#L20

**Comment by bunnyi116** [comment]
？？？原因我已早就知道了，然后我的版本很早就已经支持任意方向破坏，且无需急迫二，只需要效率5和足够材料.

**Comment by z7087** [comment]
其实仍然可以在非原版服中通过easyplace协议放置活塞达到无须等待yaw轴转头的效果

原版服可以通过制造拉回并立即应答来立即更新headyaw

> 且无需急迫二

<img width="366" height="411" alt="Image" src="https://github.com/user-attachments/assets/6bfb7117-b1d5-4954-8c6e-768c359fef3b" />
<br/>
<img width="448" height="148" alt="Image" src="https://github.com/user-attachments/assets/a9be9550-5752-49ee-9449-f9a93a0f43c4" />
