### ISSUE TITLE
I can’t use it in a server 

### ISSUE THREAD

**Issue by MXFia190** [Bunnui/Fabric-Bedrock-Miner#18]
How do I use it in a server

**Comment by Bunnui** [comment]
# Usage
Have the following items ready:
1. Efficiency V diamond (or netherite) pickaxe
2. Haste II beacon
3. Pistons
4. Redstone torches
5. Slime blocks

Right click bedrock **with an empty hand** to switch on/off.

While the mod is enabled, left click bedrock to "mine" it.

If my mod saves you tons of time, please considering leave me a star.
