### ISSUE TITLE
[功能建议] 平面向下/向上破基岩/末地传送门

### ISSUE THREAD

**Issue by Error-106** [Bunnui/Fabric-Bedrock-Miner#19]
目前模组只能向下破基岩，且破基岩时活塞下方周围四格必须为能放置红石火把的方块
![2023-08-13_10 14 20](https://github.com/Bunnui/Fabric-Bedrock-Miner/assets/92155028/3e809b60-8d6a-436d-b599-086edd67c11a)
能否尝试在无法在下方放置火把时尝试在横向放置火把
![2023-08-13_10 10 27](https://github.com/Bunnui/Fabric-Bedrock-Miner/assets/92155028/9e3a83de-e511-4cbd-a65b-8f857130ae26)
以及无法在上方破基岩时（例如破除龙巢下方基岩）尝试在下方破基岩
![2023-08-13_10 06 12](https://github.com/Bunnui/Fabric-Bedrock-Miner/assets/92155028/40a78b0b-1d4e-4d05-a1f4-0f19e6af2b1a)

**Comment by Bunnui** [comment]
目标方块下放置活塞方案可以实现，因为发送给服务器发送修改俯仰(pitch)数据包时同时发送放置方块交互数据包是可以正确放置的，但航向(yaw)角不起作用。有时间尝试写一下

技术难题：
我也很纳闷 pitch，yaw 修改数据包是一个包，是同时发送的，为啥 pitch 的值能生效，而 yaw 却存在这个问题。我也不清楚这是什么原因。

目前观察下来，只要延迟1Tick发送视角包，且客户端自己不再发送新的修改视角包（视角保持不动），即可精确放置方向，但由于模组利用活塞收回事件需要在1Tick中完成，所以无法实现其他方向放置（可能是我JAVA语言不太会，或不太了解客户端和服务端是如何保证发包间隔时，怎么保证这些数据包是在同服务端是在同1tick发包的，因为客户端和服务端是存在延迟的）。

如果说单人模式的话可以实现，因为可以直接改服务端代码，甚至直接修改代码，让基岩可以被破坏，至于多人模式情况下，那就没有办法使用了，因为没有办法修改服务端，如果服务端你可以加上兼容插件或模组，或许能实现

至于火把侧方这种方案我有想过，当由于目前技术上的问题(无法精确放置带有方向的方块) ，暂时无法实现。

**Comment by Bunnui** [comment]
技术难题还漏了一个，不知道怎么保证服务端在同1tick中先生效修改数据包后，在放置方块

**Comment by Bunnui** [comment]
今天搞了一天，越写越乱，真头疼，唉。有时间在写的，不知道怎么设计多位置的框架

**Comment by Fiz-Victor** [comment]
[这个方块放置破坏框架](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/utils/world/BlockUtils.java)里的getPlaceSide可以参考一下，照理说不会有什么放置错误

**Comment by Bunnui** [comment]
放置方向错误是因为交互方块放置的时服务端在处理交互数据包时，使用到的上一次的pitch，所以东南西北无法精确放置，但我不清楚yaw总是生效的。我可以实现精确放置，但得提前修改视角，在放置方块。

全部方向实现是可以实现，就是处理破基岩方块算法和逻辑比较混乱

![image](https://github.com/Bunnui/Fabric-Bedrock-Miner/assets/37466008/cdaf9090-916f-422b-8fe6-2fc677e63308)
![image](https://github.com/Bunnui/Fabric-Bedrock-Miner/assets/37466008/4ff57384-b5d9-4669-af66-a28cfa8f6381)

**Comment by Bunnui** [comment]
看哪天有空在重新梳理一下流程，然后重构一下代码，今天被算法和逻辑搞的头疼，然后这几天鼠标还坏了，左键点一下容易连击和断点，这是最烦的

**Comment by Error-106** [comment]
感谢尝试解决，请问有赞助链接吗

**Comment by Bunnui** [comment]
已经初步实现，暂时不知道bug。

这是实现的测试版本：https://github.com/Bunnui/Fabric-Bedrock-Miner/actions/runs/5883780769
进入actions网页后找到Artifacts附件下载即可

![群二维码](https://github.com/Bunnui/Fabric-Bedrock-Miner/assets/37466008/7f1c2bc7-876b-4d34-9534-c72a3b555a2a)

真想要赞助我加群私聊我，我发收款码，这群是刚刚建的。

**Comment by Bunnui** [comment]
又修了修，之前发的链接的视角版本有问题，然后算法也有一点小问题，我有修了修

这是新的https://github.com/Bunnui/Fabric-Bedrock-Miner/actions/runs/5885946049

其实你可以到https://github.com/Bunnui/Fabric-Bedrock-Miner/actions 自己查看最新的

**Comment by Bunnui** [comment]
已合并到主分支，正式版本：https://github.com/Bunnui/Fabric-Bedrock-Miner/releases/tag/v1.20.1-1.1.9

**Comment by Bunnui** [comment]
这是为了还原视角，在支持全方位破基岩前修改视角并固定客户端以后的视角包，为防止玩家走出处理范围导致视角未被正常流程还原，之后会导致你放置方块会朝向某个方向，为解决这个我增加了自动还原，但忘记了加个判断，所以客户端会每20tick发送一次。之后我会加入判断，让它仅在修改后执行

**Comment by Bunnui** [comment]
值得一提的是，并不建议在有反作弊的服务器中使用。

**Comment by Bunnui** [comment]
这是增加判断后的提交。文件可以在actions获取

https://github.com/Bunnui/Fabric-Bedrock-Miner/actions/runs/5945278740
