### ISSUE TITLE
Plz add rotations

### ISSUE THREAD

**Issue by ImKindaSus** [Bunnui/Fabric-Bedrock-Miner#22]
Plz add server side rotations before placing/breaking blocks for more strict servers

**Comment by Bunnui** [comment]
Before placement, a modified perspective packet is sent directly, and then the perspective packet sent by the client to the server will be locked until the processing is completed.

**Comment by Bunnui** [comment]
My English is very poor, I don't know how machine translation works

**Comment by Bunnui** [comment]
Before placement, it will send a PlayerMoveC2SPacket packet, and then perform a fixed server Look, so for the server, your perspective is fixed
